version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: juanpablopiano/vue-app-again:latest
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      # - ./node_modules:/app/node_modules
    command: npm run dev
